const data = [
  {
    id: 1,
    name: "Pasta",
    price: 5,
    category: "breakfast",
    des: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis laudantium cupiditate quaerat, voluptate minus delectus?",
    img: "https://www.listchallenges.com/f/items/57fc372f-9ae7-44e7-b35d-68c8d5bd8df0.jpg",
  },
  {
    id: 2,
    name: "French Fries",
    price: 2.5,
    category: "breakfast",
    des: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis laudantium cupiditate quaerat, voluptate minus delectus?",
    img: "https://www.listchallenges.com/f/items/f50faefe-c33e-4cf8-af58-e1ac706037a6.jpg",
  },
  {
    id: 3,
    name: "Ice Cream",
    price: 3,
    category: "breakfast",
    des: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis laudantium cupiditate quaerat, voluptate minus delectus?",
    img: "https://www.listchallenges.com/f/items/392e5f56-d7de-43e5-9c52-cf733bf1b50f.jpg",
  },
  {
    id: 4,
    name: "Bread",
    price: 1.5,
    category: "breakfast",
    des: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis laudantium cupiditate quaerat, voluptate minus delectus?",
    img: "https://www.listchallenges.com/f/items/9372fda0-ba88-475f-ae05-e8669224a704.jpg",
  },
  {
    id: 5,
    name: "Fried Rice",
    price: 10,
    category: "lunch",
    des: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis laudantium cupiditate quaerat, voluptate minus delectus?",
    img: "https://www.listchallenges.com/f/items/f516ff77-63c5-44d5-bbc4-260161586659.jpg",
  },
  {
    id: 6,
    name: "Pancakes",
    price: 6,
    category: "lunch",
    des: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis laudantium cupiditate quaerat, voluptate minus delectus?",
    img: "https://www.listchallenges.com/f/items/bc00e0dc-7106-495f-b552-e66dd6e7bd48.jpg",
  },
  {
    id: 7,
    name: "Burger",
    price: 8,
    category: "lunch",
    des: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis laudantium cupiditate quaerat, voluptate minus delectus?",
    img: "https://www.listchallenges.com/f/items/d7e7dd13-3215-452a-ab68-ac773aef252f.jpg",
  },
  {
    id: 8,
    name: "Pizza",
    price: 12,
    category: "lunch",
    des: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis laudantium cupiditate quaerat, voluptate minus delectus?",
    img: "https://www.listchallenges.com/f/items/e8bd412f-c092-4e68-8de9-c0d9710acf0d.jpg",
  },
  {
    id: 9,
    name: "Tacos",
    price: 11,
    category: "lunch",
    des: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis laudantium cupiditate quaerat, voluptate minus delectus?",
    img: "https://www.listchallenges.com/f/items/2ab012b4-8cfe-4ff9-adf5-3d455d1b4f25.jpg",
  },
  {
    id: 10,
    name: "Enchilada",
    price: 14,
    category: "dinner",
    des: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis laudantium cupiditate quaerat, voluptate minus delectus?",
    img: "https://www.listchallenges.com/f/items/15ee87cb-1abb-43aa-a903-df0051fff204.jpg",
  },
  {
    id: 11,
    name: "Chimichanga",
    price: 12,
    category: "dinner",
    des: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis laudantium cupiditate quaerat, voluptate minus delectus?",
    img: "https://www.listchallenges.com/f/items/77eff27b-9d17-4cb2-968c-dda1e106b977.jpg",
  },
  {
    id: 12,
    name: "Steak",
    price: 14,
    category: "dinner",
    des: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis laudantium cupiditate quaerat, voluptate minus delectus?",
    img: "https://www.listchallenges.com/f/items/e44505ff-3b97-44bb-833b-1eaea990463e.jpg",
  },
];

export default data;
